export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  logout: "/logout",
  landing: "/i/landing",
  expiredSession: "/i/session-expired",
  composePost: "/compose/post",
  explore: "/explore",
  search: "/search",
  notifications: "/notifications",
  connectPeople: "/i/connect_people",
  chat: "/i/chat",
  grok: "/i/grok",
  history: "/i/history",
  creatorStudio: "/i/jf/creators/studio",
  premium: "/i/premium_sign_up",
  business: "/i/verified-orgs-signup",
  spaces: "/i/spaces/start",
  settings: "/settings",
  ads: "https://ads.x.com/?ref=gl-tw-tw-twitter-ads-rweb",
  profile: (handle: string) => `/${handle}`,
  profileReplies: (handle: string) => `/${handle}/with_replies`,
  lists: (handle: string) => `/${handle}/lists`,
  communities: (handle: string) => `/${handle}/communities`,
  tweet: (handle: string, id: string) => `/${handle}/status/${id}`,
} as const;
