export const routes = {
  home: "/",
  login: "/login",
  register: "/register",
  logout: "/logout",
  landing: "/i/landing",
  expiredSession: "/i/session-expired",
  composePost: "/compose/post",
  composeReply: (tweetId: string) => `/compose/post?in_reply_to=${tweetId}`,
  composeQuote: (tweetId: string) => `/compose/post?quote=${tweetId}`,
  explore: "/explore",
  search: "/search",
  notifications: "/notifications",
  notificationsMentions: "/notifications/mentions",
  notificationsSettings: "/settings/notifications",
  settingsSessions: "/settings/sessions",
  connectPeople: "/i/connect_people",
  connectPeopleSimilarTo: (userId: string) =>
    `/i/connect_people?user_id=${userId}`,
  chat: "/i/chat",
  grok: "/i/grok",
  history: "/i/history",
  creatorStudio: "/i/jf/creators/studio",
  premium: "/i/premium_sign_up",
  business: "/i/verified-orgs-signup",
  spaces: "/i/spaces/start",
  settings: "/settings",
  ads: "https://ads.x.com/?ref=gl-tw-tw-twitter-ads-rweb",
  profile: (handle: string) => `/${handle}`,
  profileReplies: (handle: string) => `/${handle}/with_replies`,
  profileReposts: (handle: string) => `/${handle}/reposts`,
  profileMedia: (handle: string) => `/${handle}/media`,
  profileHighlights: (handle: string) => `/${handle}/highlights`,
  profilePhoto: (handle: string) => `/${handle}/photo`,
  profileHeaderPhoto: (handle: string) => `/${handle}/header_photo`,
  profileAbout: (handle: string) => `/${handle}/about`,
  following: (handle: string) => `/${handle}/following`,
  followers: (handle: string) => `/${handle}/followers`,
  verifiedFollowers: (handle: string) => `/${handle}/verified_followers`,
  followersYouFollow: (handle: string) => `/${handle}/followers_you_follow`,
  editProfile: "/settings/profile",
  bookmarks: "/i/bookmarks",
  historyLikes: "/i/history/likes",
  listCreate: "/i/lists/create",
  listAddMember: "/i/lists/add_member",
  list: (id: string) => `/i/lists/${id}`,
  listMembers: (id: string) => `/i/lists/${id}/members`,
  listFollowers: (id: string) => `/i/lists/${id}/followers`,
  listInfo: (id: string) => `/i/lists/${id}/info`,
  lists: (handle: string) => `/${handle}/lists`,
  communities: (handle: string) => `/${handle}/communities`,
  tweet: (handle: string, id: string) => `/${handle}/status/${id}`,
  tweetPhoto: (handle: string, id: string, index: number) =>
    `/${handle}/status/${id}/photo/${index}`,
  tweetQuotes: (handle: string, id: string) => `/${handle}/status/${id}/quotes`,
  tweetRetweets: (handle: string, id: string) =>
    `/${handle}/status/${id}/retweets`,
  tweetLikes: (handle: string, id: string) => `/${handle}/status/${id}/likes`,
} as const;
